# Based on https://blender.stackexchange.com/questions/76535/create-model-from-xyz-data-points
import os
import bpy
import csv
from operator import itemgetter

# Open the file generated by temp_mountain.py (run outside Blender)
current_dir = os.path.dirname(bpy.data.filepath)
csvpath = os.path.join(current_dir, 'temp_mountain_vertices.csv')
csvfile = open(csvpath)
inFile = csv.reader(csvfile, delimiter=',', quotechar='"')

# Read vertices. They'll be in time order from the file
last_vertex = None
current_vertex = None
jan_vertex = 0
current_month = 1
vertex_count = 0
vertices = []
edges = []

for row in inFile:
    current_vertex = (float(row[0]), float(row[1]), float(row[2]))
    vertices.append(current_vertex)
    if current_month == 1:
        jan_vertex = vertex_count
        
    if current_month > 1:
        edges.append((vertex_count - 1, vertex_count))
    
    current_month += 1
    if current_month > 12:
        edges.append((vertex_count, jan_vertex))
        current_month = 1
    vertex_count += 1
    
#********* Assuming we have a rectangular grid *************
xSize = next( i for i in range( len(vertices) ) if vertices[i][0] != vertices[i+1][0] ) + 1 #Find the first change in X
ySize = len(vertices) // xSize

#Generate the polygons (four vertices linked in a face)
#polygons = [(i, i - 1, i - 1 + xSize, i + xSize) for i in range( 1, len(vertices) - xSize ) if i % xSize != 0]

name = "mountain"
mesh = bpy.data.meshes.new( name ) #Create the mesh (inner data)
obj = bpy.data.objects.new( name, mesh ) #Create an object

obj.data.from_pydata( vertices, edges, [] ) #Associate vertices and polygons

#obj.scale = (1, 5, 0.2) #Scale it (if needed)
#for p in obj.data.polygons: #Set smooth shading (if needed)
#    p.use_smooth = True

bpy.context.scene.collection.objects.link( obj ) #Link the object to the scene