# Based on https://blender.stackexchange.com/questions/76535/create-model-from-xyz-data-points
import os
import bpy
import csv
from operator import itemgetter

# Open the file generated by temp_mountain.py (run outside Blender)
current_dir = os.path.dirname(bpy.data.filepath)
csvpath = os.path.join(current_dir, 'temp_mountain_vertices.csv')
csvfile = open(csvpath)
inFile = csv.reader(csvfile, delimiter=',', quotechar='"')
rows = list(inFile)

# Read vertices. They'll be in time order from the file
current_row = 0
last_vertex_outer = None
last_vertex_inner = None
jan_vertex_outer = None
jan_vertex_inner = None
current_month = 1

vertices = []
polygons = []

while current_row < len(rows):
    outer = rows[current_row]
    inner = rows[current_row + 1]
    vertices.append((float(outer[0]), float(outer[1]), float(outer[2])))
    vertices.append((float(inner[0]), float(inner[1]), float(inner[2])))
    
    if current_month == 1:
        jan_vertex_outer = current_row
        jan_vertex_inner = current_row + 1
    else:
        polygons.append((last_vertex_outer, last_vertex_inner, current_row + 1, current_row))
        
    current_month += 1
    if current_month > 12:
        polygons.append((current_row, current_row + 1, jan_vertex_inner, jan_vertex_outer))
        last_vertex_outer = None
        last_vertex_inner = None
        current_month = 1
    else:
        last_vertex_outer = current_row
        last_vertex_inner = current_row + 1
        
    current_row += 2

name = "mountain"
mesh = bpy.data.meshes.new( name ) #Create the mesh (inner data)
obj = bpy.data.objects.new( name, mesh ) #Create an object
obj.data.from_pydata( vertices, [], polygons ) #Associate vertices and polygons
bpy.context.scene.collection.objects.link( obj ) #Link the object to the scene